FactoryBot.define do
  factory :event do
    association :event_category
    association :user

    sequence(:title) { |n| "Event #{n}" }
    description { "Event generated by FactoryBot" }
    start_time { Time.current }
    end_time { Time.current + 2.hours }
    visibility { "private" }
    location { "Test Location" }
  end
end
