class Event < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_one_attached :cover_image
  has_many_attached :files

  belongs_to :group, optional: true
  belongs_to :event_category
  belongs_to :user, class_name: "User", foreign_key: "user_id", inverse_of: :owned_events
  has_many :event_participations, dependent: :destroy
  has_many :users, through: :event_participations
  has_many :event_suggestions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  before_validation :assign_default_category

  validates :title, :start_time, :end_time, presence: true
  validate :validate_file_sizes

  enum :visibility, { private: "private", friends: "friends" }, prefix: true

  has_rich_text :description

  def self.for_user(user)
    own_or_participating = left_joins(:event_participations)
                             .where("event_participations.user_id = ? OR events.user_id = ?", user.id, user.id)
                             .where("event_participations.rsvp_status IN (?)", ["accepted", "maybe"])
                             .to_sql
    friends_visible = visible_for_friend(user).to_sql

    Event.from("(#{own_or_participating} UNION #{friends_visible}) AS events").order("start_time DESC")
  end

  def past?
    end_time < Time.current
  end

  # Force regenerate slug if title changes
  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end

  def self.visible_for_friend(user)
    where(visibility: "friends")
      .joins("INNER JOIN friendships ON (friendships.user_id = events.user_id OR friendships.friend_id = events.user_id)")
      .where("friendships.user_id = :id OR friendships.friend_id = :id", id: user.id)
  end

  def self.past(user)
    own_or_participating = left_joins(:event_participations)
                             .where("event_participations.user_id = ? OR events.user_id = ?", user.id, user.id)
                             .where("event_participations.rsvp_status IN (?)", ["accepted", "maybe"])
                             .to_sql
    friends_visible = visible_for_friend(user).to_sql

    Event.where("start_time < ?", Date.today).from("(#{own_or_participating} UNION #{friends_visible}) AS events").order("start_time DESC")
  end

  def self.upcoming(user)
    ### Events that the user owns or is participating in with status accepted or maybe
    Event.for_user(user).where("start_time >= ?", Date.today)
  end

  def add_friend_with_rsvp(user, rsvp_status = "pending")
    event_participations.create(user: user, rsvp_status: rsvp_status)
  end

  def owned_by?(current_user)
    user == current_user
  end

  private

  def assign_default_category
    self.event_category ||= EventCategory.find_by(name: "Other") || EventCategory.create(name: "Other", emoji: "📅", description: "General events")
  end

  def validate_file_sizes
    files.each do |file|
      if file.byte_size > 10.megabytes
        errors.add(:files, "#{file.filename} is too large. Each file must be under 10 MB.")
      end
    end
  end

  # def send_event_created_push_notification
  #   # Fetch FCM tokens of all users participating in the event except the creator
  #   fcm_tokens = users.where.not(id: user.id).pluck(:fcm_token).compact

  #   return if fcm_tokens.empty?

  #   fcm = FCM.new(Rails.application.credentials.dig(:fcm, :server_key))

  #   options = {
  #     notification: {
  #       title: "New Event: #{title}",
  #       body: "#{user.first_name} #{user.last_name} has created a new event.",
  #       sound: "default"
  #     },
  #     data: {
  #       event_id: id,
  #       event_title: title,
  #       event_start_time: start_time.iso8601
  #     }
  #   }
  # FcmService.new.send_notification(User.first.fcm_token, title: "New event", body: User.first.full_name, data: {event_id: event.id.to_s}

  #   # Code generated by chat gpt
  #   #     if @event.save
  #   #   # notify all friends
  #   #   current_api_user.friends.each do |friend|
  #   #     if friend.fcm_token.present?
  #   #       FcmService.new.send_notification(
  #   #         friend.fcm_token,
  #   #         title: "New Event 🎉",
  #   #         body: "#{current_api_user.name} created #{@event.title}",
  #   #         data: { event_id: @event.id.to_s }
  #   #       )
  #   #     end
  #   #   end
  #   # end
  #   response = fcm.send(fcm_tokens, options)
  #   Rails.logger.info("FCM Response: #{response}")
  # rescue => e
  #   Rails.logger.error("Failed to send FCM notification: #{e.message}")
end
